import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteLayout } from "@/components/layouts";
import { ProductCard } from "@/components/product-card";
import { Button } from "@/components/ui/button";
import { useCatalogData } from "@/lib/catalog-data";
import { ArrowRight, Layers } from "lucide-react";

export const Route = createFileRoute("/")({ component: HomePage });

function HomePage() {
  const { data, loading, error } = useCatalogData();
  const products = data?.products ?? []; const categories = data?.categories ?? []; const creators = data?.creators ?? [];
  return <SiteLayout>
    <section className="relative overflow-hidden"><div className="absolute inset-0 gradient-hero" /><div className="absolute inset-0 grid-dots opacity-40" /><div className="relative mx-auto max-w-[1440px] px-4 md:px-6 py-24 md:py-36 text-center"><h1 className="text-4xl md:text-7xl font-semibold tracking-tight">The marketplace <span className="gradient-text">built for developers</span></h1><p className="mt-6 text-lg text-muted-foreground max-w-2xl mx-auto">Discover and publish production-ready developer products from independent creators.</p><div className="mt-8 flex justify-center gap-3"><Button asChild size="lg" className="gradient-brand text-white"><Link to="/marketplace">Explore marketplace <ArrowRight className="ml-2 size-4" /></Link></Button><Button asChild size="lg" variant="outline"><Link to="/creator">Become a creator</Link></Button></div><div className="mt-16 grid grid-cols-3 gap-4 max-w-3xl mx-auto">{[{label:"Products",value:products.length},{label:"Creators",value:creators.length},{label:"Categories",value:categories.length}].map((item) => <div key={item.label} className="glass rounded-2xl p-5"><div className="text-3xl font-semibold gradient-text">{item.value}</div><div className="text-xs uppercase tracking-wider text-muted-foreground">{item.label}</div></div>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-4 md:px-6 py-16"><div className="flex items-end justify-between"><div><h2 className="text-2xl font-semibold">Published products</h2><p className="text-muted-foreground">Products available from real creators.</p></div><Link to="/marketplace" className="text-sm text-muted-foreground hover:text-foreground">View all</Link></div>{loading ? <p className="py-12 text-muted-foreground">Loading catalog…</p> : products.length ? <div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,8).map((product) => <ProductCard key={product.id} product={product} />)}</div> : <div className="mt-6 card-elegant rounded-2xl py-16 text-center"><h3 className="text-lg font-medium">No published products yet</h3><p className="mt-2 text-sm text-muted-foreground">Be the first creator to publish.</p><Button asChild className="mt-5 gradient-brand text-white"><Link to="/creator">Open Creator Dashboard</Link></Button></div>}{error && <p className="mt-4 text-sm text-destructive">Catalog temporarily unavailable.</p>}</section>
    <section className="border-y bg-muted/20"><div className="mx-auto max-w-[1440px] px-4 md:px-6 py-16"><h2 className="text-2xl font-semibold">Browse categories</h2><div className="mt-6 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">{categories.slice(0,12).map((category) => <Link key={category.slug} to="/category/$slug" params={{ slug: category.slug }} className="card-elegant rounded-xl p-4"><Layers className="size-4 text-primary" /><p className="mt-3 font-medium">{category.name}</p><p className="text-xs text-muted-foreground">{category.count} products</p></Link>)}</div></div></section>
    <section className="mx-auto max-w-[1440px] px-4 md:px-6 py-20 text-center"><h2 className="text-3xl font-semibold">Share what you build.</h2><p className="mt-3 text-muted-foreground">Create your profile, save drafts, and publish when ready.</p><Button asChild size="lg" className="mt-6 gradient-brand text-white"><Link to="/creator">Start publishing</Link></Button></section>
  </SiteLayout>;
}
