CREATE TABLE IF NOT EXISTS categories (
  slug TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  group_name TEXT NOT NULL DEFAULT 'Products'
);

CREATE TABLE IF NOT EXISTS products (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  tagline TEXT NOT NULL,
  category TEXT NOT NULL,
  price REAL NOT NULL DEFAULT 0,
  free INTEGER NOT NULL DEFAULT 0,
  open_source INTEGER NOT NULL DEFAULT 0,
  premium INTEGER NOT NULL DEFAULT 0,
  enterprise INTEGER NOT NULL DEFAULT 0,
  rating REAL NOT NULL DEFAULT 0,
  reviews INTEGER NOT NULL DEFAULT 0,
  sales INTEGER NOT NULL DEFAULT 0,
  downloads INTEGER NOT NULL DEFAULT 0,
  views INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  version TEXT NOT NULL,
  gradient TEXT NOT NULL,
  emoji TEXT NOT NULL,
  tech TEXT NOT NULL,
  description TEXT NOT NULL,
  creator TEXT NOT NULL,
  trending INTEGER NOT NULL DEFAULT 0,
  new INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS creators (
  id TEXT PRIMARY KEY,
  handle TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  avatar TEXT NOT NULL,
  verified INTEGER NOT NULL DEFAULT 0,
  followers INTEGER NOT NULL DEFAULT 0,
  sales INTEGER NOT NULL DEFAULT 0,
  rating REAL NOT NULL DEFAULT 0,
  bio TEXT NOT NULL,
  location TEXT NOT NULL,
  joined TEXT NOT NULL,
  organization TEXT
);
